# Generated by Django 3.0.6 on 2021-01-27 09:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Nazwa')),
                ('description', models.TextField(verbose_name='Opis ćwiczenia')),
                ('link', models.CharField(max_length=120, verbose_name='Link do You Tube')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_reps', models.IntegerField(verbose_name='Liczba powtórzeń w serii')),
                ('exercise_rounds', models.IntegerField(verbose_name='Liczba serii')),
                ('exercise_weight', models.FloatField(null=True, verbose_name='Obciążenie')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Data rozpoczęcia')),
                ('finish_date', models.DateField(null=True, verbose_name='Data zakończenia')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gym.Exercise')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(verbose_name='Wiek')),
                ('height', models.IntegerField(verbose_name='Wzrost')),
                ('weight', models.FloatField(verbose_name='Waga')),
                ('muscle_weight', models.FloatField(null=True, verbose_name='Waga mięśni')),
                ('fat_weight', models.FloatField(null=True, verbose_name='Waga tłuszczu')),
                ('metabolic_age', models.IntegerField(null=True, verbose_name='Wiek metaboliczny')),
                ('chest_circuit', models.FloatField(null=True, verbose_name='Obwód klatki piersiowej')),
                ('biceps_circuit', models.FloatField(null=True, verbose_name='Obwód bicepsa')),
                ('biceps_circuit_tight', models.FloatField(null=True, verbose_name='Obwód bicepsa w spięciu')),
                ('buttock_circuit', models.FloatField(null=True, verbose_name='Obwód pośladka')),
                ('thigh_circuit', models.FloatField(null=True, verbose_name='Obwód uda')),
                ('waist_circuit', models.FloatField(null=True, verbose_name='Obwód talii')),
                ('calf_circuit', models.FloatField(null=True, verbose_name='Obwód łydki')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Data pomiarów')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Nazwa planu')),
                ('exercise', models.ManyToManyField(through='Gym.ExerciseSet', to='Gym.Exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik planu')),
            ],
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='training_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gym.TrainingPlan'),
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ExerciseHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_reps', models.IntegerField(verbose_name='Suma powtórzeń')),
                ('weight', models.FloatField(verbose_name='Obciążenie')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Data treningu')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gym.Exercise', verbose_name='Ćwiczenie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
        ),
    ]
